language: bash

services:
- docker

env:
- MEMCACHED_VER=1.6.7 TAGS=1.6,1,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
