name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  MEMCACHED1: '1.6.39'

jobs:
  memcached1-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm            
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          MEMCACHED_VER: ${{ env.MEMCACHED1 }}
          ARCH: ${{ matrix.arch }}
        run: |
          make
          make test
          make push
  memcached1-push:
    runs-on: ubuntu-latest
    needs:
      - memcached1-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MEMCACHED1 }}
          latest: true
          latest_major: true
