name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  MEMCACHED1: '1.6.15'

jobs:
  memcached-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.MEMCACHED1 }}
        tags: 1,latest
        alpine_ver: 3.15
  memcached-1-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.MEMCACHED1 }}
        tags: 1-alpine3.13,alpine3.13
        alpine_ver: 3.13
