name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

jobs:
  memcached-16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 1.6.8
        tags: 1.6,1,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
